---
xOrgConfFileName: "/etc/X11/xorg.conf.d/00-keyboard.conf"
convertedKeymapPath: "/lib/kbd/keymaps/xkb"
configure:
    kwin: false
    gnome: true
keyboardModels:
    - name: pc105
      description: "Generic 105-key"
    - name: pc104
      description: "Generic 104-key"
keyboards:
    - es
    - latam
    - us
