---
efi:
    mountPoint:         "/boot"
    recommendedSize:    512MiB
    minimumSize:        100MiB
    label:              "X"

userSwapChoices:
    - none
    - small
    - suspend
    - file

initialSwapChoice: small

defaultFileSystemType: btrfs

alwaysShowPartitionLabels: true
enableLuksAutomatedPartitioning: true
enableLuksAsync: true
luksSwap: true
