---
showSupportUrl:         true
showKnownIssuesUrl:     true
showReleaseNotesUrl:    true
showDonateUrl:          false

requirements:
    requiredStorage:    10
    requiredRam:        2.0
    internetCheckUrl:   https://xscriptor.io/x
    check:
        - storage
        - ram
        - internet
